### PR TITLE
Updates

### LINKED ISSUE #37: use Node.js 16
When using the action lately, I get the following warning in my GitHub workflows:

```Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Sibz/github-status-action, Sibz/github-status-action```

Could you please update the project so that it uses Node.js 16?

### PR DESCRIPTION
**Pull request by dobladov**
The action needs to be updated in order to keep workig: https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/

- Use `@vercel/ncc` instead of deprecated `@zeit/ncc`
- Upgrade to node `16`
- Upgraded typescript and types
- Use `createCommitStatus` instead of deprecated `createCommit`
- Use `actions/checkout@v3`

Fixes: #37

### CODE REVIEW

**Comment by rmichalak** [comment]
I gave it a try and I got this error:
```
Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
```
You may want to downgrade to node16

**Comment by dobladov** [comment]
I was unsure if `node20` was supported, I will downgrade to `node16`
https://github.com/actions/runner/issues/2619

**Comment by MikeMcC399** [comment]
Currently only `node16` is supported. See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions

**Comment by ragmondo** [comment]
@dobladov Can you publish your action please ? It looks as if this repo is not being actively maintained.

**Comment by dobladov** [comment]
@ragmondo I would still prefer if @Sibz continues being the maintainer, I'm not as knowledgable about the action internals, I only did some maintenance work for this PR.

I published my version on the marketplace, in case this repository stays unmaintained.
https://github.com/marketplace/actions/action-status

You can use the action with `dobladov/github-status-action@2.0.0`, usage should be the same.

I will do some testing tomorrow to see if it works properly.

**Review by guibranco — APPROVED** [review]

**Comment by Sibz** [comment]
> @dobladov Can you publish your action please ? It looks as if this repo is not being actively maintained.

Sorry been away and isolated from the internet. I have some catching up to do.

**Comment by Sibz** [comment]
@dobladov I've added you as a collaborator as I do need help, I'm a bit overwhelmed at the moment.

**Comment by dobladov** [comment]
@guibranco thanks for approving, I still need someone to approve the check before merging.

**Review by vhsantos26 — APPROVED** [review]

**Comment by dobladov** [comment]
Still can't merge.

Screenshot 2023-06-30 at 10 54 28

**Comment by dobladov** [comment]
In case it helps others, here is an alternative solution to create statuses, currently using node `16` and [soon](https://github.com/octokit/request-action/pull/293) using node `20`.

More info about the request: https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status

```yml
  - name: Create status
    uses: octokit/request-action@v2.x
    with:
      route: POST /repos/{owner}/{repo}/statuses/{sha}
      owner: ${{ github.repository_owner }}
      repo: '${{ github.event.repository.name }}'
      sha: ${{ github.sha }}
      state: error, failure, pending, success
      target_url: ${{ env.JOB_URL }}
      context: ${{ env.STATUS_DESCRIPTION }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by guibranco** [comment]
@dobladov I am currently using an updated V2 version (a fork of this). If anyone is interested in trying it out, please use this URL: https://github.com/guibranco/github-status-action-v2.

I am curious to know whether the owner of this repository will return to approve or merge these PRs, or if they have abandoned all projects in their account. Their last activity on GitHub was in August 2023, and the last commit to this repository was over three years ago.

**Pull request closed without merging**
